// <auto-generated />
namespace Durandal_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialmigrationforDurandalDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialmigrationforDurandalDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201604162125137_Initial migration for DurandalDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
